### ISSUE TITLE
Downloading resource bag fails

### ISSUE THREAD

**Issue by horsburgh** [sblack-usu/hs_rdf#4]
I'm getting an error when trying to download the resource Bag. It's related to the addition of the citation metadata element. I have not set a citation - but I shouldn't have to. The default citation should be set within the resource metadata automatically.

![image](https://user-images.githubusercontent.com/3485902/102701923-8f41c580-4219-11eb-8c6d-b55e149e2b1e.png)

**Comment by sblack-usu** [comment]
Pretty sure this is due to the resource already existing.  To get citations in the rdf/xml for each resource, I have to regenerate it for each resource, which I have not done since citations was added.  It should work fine for new resources, or you can regenerate the rdf/xml by editing the metadata of the resource.  If you're working with timeseries of an existing resource, you'll have to edit the metadata to regenerate it as well.  Once the dust settles, I'll regenerate all the rdf/xml for all the resources, but for now you'll have to be careful what you access.
